name: Build PyPI Package on Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout_repository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        id: install_dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
        shell: bash
        continue-on-error: false

      - name: Run tests
        id: run_tests
        run: |
          sed -i 's/test_api_key = ""/test_api_key = "'"${{ secrets.PEXELS_API_KEY }}"'"/' tests/test_pexels_api.py
          pytest --maxfail=1 --disable-warnings tests/test_pexels_api.py
        shell: bash
        continue-on-error: false

      - name: Build the package
        id: build_package
        run: |
          python -m build
          if [ $? -ne 0 ]; then
            echo "Build failed"
            exit 1
          fi
        shell: bash

      - name: Show built files
        id: show_built_files
        run: ls dist
        shell: bash
