name: Build and Upload PyPI Package on Production Merge

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pexels-api
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
        shell: bash

      - name: Build the package
        run: python -m build
        shell: bash

      - name: Extract package version
        id: get_version
        run: |
          version=$(python setup.py --version)
          echo "PACKAGE_VERSION=${version}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Show built files
        run: ls dist
        shell: bash

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          verbose: true